language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '10.15.3'
script:
  yarn global add solhint
  yarn lint
  yarn generate
  yarn ganache
  sleep 5
  yarn test
  yarn stop