/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "MyContract_v0"): TruffleContracts.MyContract_v0Contract;
      require(name: "MyContract_v1"): TruffleContracts.MyContract_v1Contract;
    }
  }
}
